name: EKS Component Version Updater

on:
  schedule:
    # Run every 10 days
    - cron: '0 0 */10 * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate branch name
        id: branch-name
        run: |
          echo "BRANCH_NAME=version-update-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create new branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.branch-name.outputs.BRANCH_NAME }}
          sha: '${{ github.sha }}'

      - name: Checkout new branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.BRANCH_NAME }}

      - name: Update component versions
        id: update-versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_component_versions.py

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          else
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update component versions $(date +'%Y-%m-%d')"
          branch: ${{ steps.branch-name.outputs.BRANCH_NAME }}
          file_pattern: 'config/metadata.json'
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          push_options: '--force'

      - name: Create Pull Request
        if: steps.git-check.outputs.CHANGES == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update component versions"
          title: "chore: update component versions $(date +'%Y-%m-%d')"
          body: |
            This PR updates the following components to their latest versions:

            ${{ steps.update-versions.outputs.changes }}

            This PR was automatically generated by the EKS Component Version Updater workflow.
          branch: ${{ steps.branch-name.outputs.BRANCH_NAME }}
          base: main
          delete-branch: false
          labels: |
            version-update
            automated-pr
